language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - iojs

install:
  - npm install

script:
  - npm run travis

after_script:
  - npm install coveralls
  - npm install mocha-lcov-reporter
  - npm run coveralls
